PROJECT_NAME = socialloot
PACKAGE = github.com/KeKsBoTer/$(PROJECT_NAME)/cmd/$(PROJECT_NAME)

all: build run

build:
	go build -o $(PROJECT_NAME) -v $(PACKAGE)

run:
	./$(PROJECT_NAME) -http 8080

clean:
	go clean $(PACKAGE)

deps:
	go get "github.com/gorilla/mux" "github.com/oxtoacart/bpool"
			